#ifndef __EXPORTS_H__
#define __EXPORTS_H__


EXPORT(npBasicAbortGui, 0x481ce0e8); /* sceNp */
EXPORT(npBasicAddBlockListEntry, 0x1ae8a549); /* sceNp */
EXPORT(npBasicAddFriend, 0x27c69eba); /* sceNp */
EXPORT(npBasicAddPlayersHistory, 0x168a3117); /* sceNp */
EXPORT(npBasicAddPlayersHistoryAsync, 0xbcdbb2ab); /* sceNp */
EXPORT(npBasicGetBlockListEntry, 0xf2b3338a); /* sceNp */
EXPORT(npBasicGetBlockListEntryCount, 0x73931bd0); /* sceNp */
EXPORT(npBasicGetClanMessageEntry, 0x4d9c615d); /* sceNp */
EXPORT(npBasicGetClanMessageEntryCount, 0xbf607ec6); /* sceNp */
EXPORT(npBasicGetCustomInvitationEntry, 0xd053f113); /* sceNp */
EXPORT(npBasicGetCustomInvitationEntryCount, 0xa8afa7d4); /* sceNp */
EXPORT(npBasicGetEvent, 0xe035f7d6); /* sceNp */
EXPORT(npBasicGetFriendListEntry, 0x04372385); /* sceNp */
EXPORT(npBasicGetFriendListEntryCount, 0xafef640d); /* sceNp */
EXPORT(npBasicGetFriendPresenceByIndex, 0x32c78a6a); /* sceNp */
EXPORT(npBasicGetFriendPresenceByIndex2, 0x6453b27b); /* sceNp */
EXPORT(npBasicGetFriendPresenceByNpId, 0xfd39ae13); /* sceNp */
EXPORT(npBasicGetFriendPresenceByNpId2, 0x260caedd); /* sceNp */
EXPORT(npBasicGetMatchingInvitationEntry, 0x05af1cb8); /* sceNp */
EXPORT(npBasicGetMatchingInvitationEntryCount, 0xaf505def); /* sceNp */
EXPORT(npBasicGetMessageAttachmentEntry, 0x5d543bbe); /* sceNp */
EXPORT(npBasicGetMessageAttachmentEntryCount, 0x9153bdf4); /* sceNp */
EXPORT(npBasicGetMessageEntry, 0x30d1cbde); /* sceNp */
EXPORT(npBasicGetMessageEntryCount, 0xecd503de); /* sceNp */
EXPORT(npBasicGetPlayersHistoryEntry, 0xbab91fc9); /* sceNp */
EXPORT(npBasicGetPlayersHistoryEntryCount, 0xa15f35fe); /* sceNp */
EXPORT(npBasicMarkMessageAsUsed, 0xe1c9f675); /* sceNp */
EXPORT(npBasicRecvMessageAttachment, 0xb5cb2d56); /* sceNp */
EXPORT(npBasicRecvMessageAttachmentLoad, 0x64a704cc); /* sceNp */
EXPORT(npBasicRecvMessageCustom, 0x806960ab); /* sceNp */
EXPORT(npBasicRegisterContextSensitiveHandler, 0x4026eac5); /* sceNp */
EXPORT(npBasicRegisterHandler, 0xbcc09fe7); /* sceNp */
EXPORT(npBasicSendMessage, 0xec0a1fbf); /* sceNp */
EXPORT(npBasicSendMessageAttachment, 0x43b989f5); /* sceNp */
EXPORT(npBasicSendMessageGui, 0x01fbbc9b); /* sceNp */
EXPORT(npBasicSetPresence, 0x3f0808aa); /* sceNp */
EXPORT(npBasicSetPresenceDetails, 0xbe81c71c); /* sceNp */
EXPORT(npBasicSetPresenceDetails2, 0x5e849303); /* sceNp */
EXPORT(npBasicUnregisterHandler, 0xacb9ee8e); /* sceNp */
EXPORT(npCommerceCreateCtx, 0xfcac355a); /* sceNp */
EXPORT(npCommerceDestroyCtx, 0xe2877bea); /* sceNp */
EXPORT(npCommerceDestroyProductCategory, 0x6cb81eb2); /* sceNp */
EXPORT(npCommerceDoCheckoutFinishAsync, 0xaf3eba5a); /* sceNp */
EXPORT(npCommerceDoCheckoutStartAsync, 0xe36c660e); /* sceNp */
EXPORT(npCommerceGetCategoryDescription, 0x359642a6); /* sceNp */
EXPORT(npCommerceGetCategoryId, 0xaee8cf71); /* sceNp */
EXPORT(npCommerceGetCategoryImageURL, 0x9452f4f8); /* sceNp */
EXPORT(npCommerceGetCategoryInfo, 0xeb9df054); /* sceNp */
EXPORT(npCommerceGetCategoryName, 0x6e2ab18b); /* sceNp */
EXPORT(npCommerceGetChildCategoryInfo, 0xba65de6d); /* sceNp */
EXPORT(npCommerceGetChildProductSkuInfo, 0x01cd9cfd); /* sceNp */
EXPORT(npCommerceGetCurrencyCode, 0x79225aa3); /* sceNp */
EXPORT(npCommerceGetCurrencyDecimals, 0xaf57d9c9); /* sceNp */
EXPORT(npCommerceGetCurrencyInfo, 0xb1c02d66); /* sceNp */
EXPORT(npCommerceGetDataFlagAbort, 0x0561448b); /* sceNp */
EXPORT(npCommerceGetDataFlagFinish, 0x9281e87a); /* sceNp */
EXPORT(npCommerceGetDataFlagStart, 0xdbdb909f); /* sceNp */
EXPORT(npCommerceGetDataFlagState, 0xd03cea35); /* sceNp */
EXPORT(npCommerceGetNumOfChildCategory, 0x2be41ece); /* sceNp */
EXPORT(npCommerceGetNumOfChildProductSku, 0x7208dc08); /* sceNp */
EXPORT(npCommerceGetProductCategoryAbort, 0x674bb9ff); /* sceNp */
EXPORT(npCommerceGetProductCategoryFinish, 0xcfd469e4); /* sceNp */
EXPORT(npCommerceGetProductCategoryResult, 0x3f195b3a); /* sceNp */
EXPORT(npCommerceGetProductCategoryStart, 0x26f33146); /* sceNp */
EXPORT(npCommerceGetProductId, 0x936df4aa); /* sceNp */
EXPORT(npCommerceGetProductName, 0xeb5f2544); /* sceNp */
EXPORT(npCommerceGetSkuDescription, 0xa85a4951); /* sceNp */
EXPORT(npCommerceGetSkuId, 0x39a69619); /* sceNp */
EXPORT(npCommerceGetSkuImageURL, 0xccbe2e69); /* sceNp */
EXPORT(npCommerceGetSkuName, 0xee530059); /* sceNp */
EXPORT(npCommerceGetSkuPrice, 0x78d7f9ad); /* sceNp */
EXPORT(npCommerceGetSkuUserData, 0x1a3fcb69); /* sceNp */
EXPORT(npCommerceInitProductCategory, 0x8d1d096c); /* sceNp */
EXPORT(npCommerceSetDataFlagFinish, 0x8d4518a0); /* sceNp */
EXPORT(npCommerceSetDataFlagStart, 0x99ac9952); /* sceNp */
EXPORT(npCustomMenuActionSetActivation, 0xf9732ac8); /* sceNp */
EXPORT(npCustomMenuRegisterActions, 0x45f8f3aa); /* sceNp */
EXPORT(npCustomMenuRegisterExceptionList, 0x9458f464); /* sceNp */
EXPORT(npDrmExecuteGamePurchase, 0xf283c143); /* sceNp */
EXPORT(npDrmGetTimelimit, 0xcf51864b); /* sceNp */
EXPORT(npDrmIsAvailable, 0xad218faf); /* sceNp */
EXPORT(npDrmIsAvailable2, 0xf042b14f); /* sceNp */
EXPORT(npDrmProcessExitSpawn, 0xaa16695f); /* sceNp */
EXPORT(npDrmProcessExitSpawn2, 0xe6c8f3f9); /* sceNp */
EXPORT(npDrmVerifyUpgradeLicense, 0x2ecd48ed); /* sceNp */
EXPORT(npDrmVerifyUpgradeLicense2, 0xbe0e3ee2); /* sceNp */
EXPORT(npFriendlist, 0xf0a9182b); /* sceNp */
EXPORT(npFriendlistAbortGui, 0xf59e1da8); /* sceNp */
EXPORT(npFriendlistCustom, 0xd7fb1fa6); /* sceNp */
EXPORT(npInit, 0xbd28fdbf); /* sceNp */
EXPORT(npLookupAbortTransaction, 0x3d1760dc); /* sceNp */
EXPORT(npLookupAvatarImage, 0xb6017827); /* sceNp */
EXPORT(npLookupAvatarImageAsync, 0xbf9eea93); /* sceNp */
EXPORT(npLookupCreateTitleCtx, 0xce81c7f0); /* sceNp */
EXPORT(npLookupCreateTransactionCtx, 0xea2e9ffc); /* sceNp */
EXPORT(npLookupDestroyTitleCtx, 0x5de61626); /* sceNp */
EXPORT(npLookupDestroyTransactionCtx, 0xfb87cf5e); /* sceNp */
EXPORT(npLookupInit, 0x5f2d9257); /* sceNp */
EXPORT(npLookupNpId, 0x166dcc11); /* sceNp */
EXPORT(npLookupNpIdAsync, 0xd12e40ae); /* sceNp */
EXPORT(npLookupPollAsync, 0x7508112e); /* sceNp */
EXPORT(npLookupSetTimeout, 0x71e5af7e); /* sceNp */
EXPORT(npLookupTerm, 0x8440537c); /* sceNp */
EXPORT(npLookupTitleSmallStorage, 0xca39c4b2); /* sceNp */
EXPORT(npLookupTitleSmallStorageAsync, 0x860b1756); /* sceNp */
EXPORT(npLookupTitleStorage, 0x9ee9f97e); /* sceNp */
EXPORT(npLookupTitleStorageAsync, 0x5e117ed5); /* sceNp */
EXPORT(npLookupUserProfile, 0xdfd63b62); /* sceNp */
EXPORT(npLookupUserProfileAsync, 0xff0a2378); /* sceNp */
EXPORT(npLookupUserProfileWithAvatarSize, 0x2fccbfe0); /* sceNp */
EXPORT(npLookupUserProfileWithAvatarSizeAsync, 0x1fdb3ec2); /* sceNp */
EXPORT(npLookupWaitAsync, 0xd737fd2d); /* sceNp */
EXPORT(npManagerGetAccountAge, 0x168fcece); /* sceNp */
EXPORT(npManagerGetAccountRegion, 0xb1e0718b); /* sceNp */
EXPORT(npManagerGetAvatarUrl, 0x36d0c2c5); /* sceNp */
EXPORT(npManagerGetCachedInfo, 0x4b9efb7a); /* sceNp */
EXPORT(npManagerGetChatRestrictionFlag, 0xeb7a3d84); /* sceNp */
EXPORT(npManagerGetContentRatingFlag, 0x6ee62ed2); /* sceNp */
EXPORT(npManagerGetEntitlementById, 0xa1709abd); /* sceNp */
EXPORT(npManagerGetEntitlementIdList, 0xb66d1c46); /* sceNp */
EXPORT(npManagerGetMyLanguages, 0x32200389); /* sceNp */
EXPORT(npManagerGetNetworkTime, 0xbdc07fd5); /* sceNp */
EXPORT(npManagerGetNpId, 0xfe37a7f4); /* sceNp */
EXPORT(npManagerGetOnlineId, 0xbe07c708); /* sceNp */
EXPORT(npManagerGetOnlineName, 0xf42c0df8); /* sceNp */
EXPORT(npManagerGetPsHandle, 0x16f88a6f); /* sceNp */
EXPORT(npManagerGetStatus, 0xa7bff757); /* sceNp */
EXPORT(npManagerGetTicket, 0x0968aa36); /* sceNp */
EXPORT(npManagerGetTicketParam, 0x58fa4fcd); /* sceNp */
EXPORT(npManagerRegisterCallback, 0xe7dcd3b4); /* sceNp */
EXPORT(npManagerRequestTicket, 0x7e2fef28); /* sceNp */
EXPORT(npManagerRequestTicket2, 0x8297f1ec); /* sceNp */
EXPORT(npManagerSubSignin, 0x442381f7); /* sceNp */
EXPORT(npManagerSubSigninAbortGui, 0x60440c73); /* sceNp */
EXPORT(npManagerSubSignout, 0x000e53cc); /* sceNp */
EXPORT(npManagerUnregisterCallback, 0x52a6b523); /* sceNp */
EXPORT(npMatchingAcceptInvitationGUI, 0x2ad7837d); /* sceNp */
EXPORT(npMatchingCreateCtx, 0xac66568c); /* sceNp */
EXPORT(npMatchingCreateRoomGUI, 0x3cc8588a); /* sceNp */
EXPORT(npMatchingDestroyCtx, 0x2e1c5068); /* sceNp */
EXPORT(npMatchingGetResult, 0x03c741a7); /* sceNp */
EXPORT(npMatchingGetResultGUI, 0x26b3bc94); /* sceNp */
EXPORT(npMatchingGetRoomInfo, 0x691f429d); /* sceNp */
EXPORT(npMatchingGetRoomInfoNoLimit, 0xb020684e); /* sceNp */
EXPORT(npMatchingGetRoomListLimitGUI, 0xe24eea19); /* sceNp */
EXPORT(npMatchingGetRoomMemberListLocal, 0x73a2e36b); /* sceNp */
EXPORT(npMatchingGetRoomSearchFlag, 0xee64cf8e); /* sceNp */
EXPORT(npMatchingGrantOwnership, 0xdae2d351); /* sceNp */
EXPORT(npMatchingJoinRoomGUI, 0x474b7b13); /* sceNp */
EXPORT(npMatchingKickRoomMember, 0x34cc0ca4); /* sceNp */
EXPORT(npMatchingKickRoomMemberWithOpt, 0xd20d7798); /* sceNp */
EXPORT(npMatchingLeaveRoom, 0xf806c54c); /* sceNp */
EXPORT(npMatchingQuickMatchGUI, 0x14497465); /* sceNp */
EXPORT(npMatchingSearchJoinRoomGUI, 0x32febb4c); /* sceNp */
EXPORT(npMatchingSendInvitationGUI, 0x8b7bbd73); /* sceNp */
EXPORT(npMatchingSetRoomInfo, 0x6f8fd267); /* sceNp */
EXPORT(npMatchingSetRoomInfoNoLimit, 0x4a18a89e); /* sceNp */
EXPORT(npMatchingSetRoomSearchFlag, 0xa284bd1d); /* sceNp */
EXPORT(npProfileAbortGui, 0x2f2c6b3e); /* sceNp */
EXPORT(npProfileCallGui, 0xceeebc7a); /* sceNp */
EXPORT(npScoreAbortTransaction, 0xee5b20d9); /* sceNp */
EXPORT(npScoreCensorComment, 0x7deb244c); /* sceNp */
EXPORT(npScoreCensorCommentAsync, 0x7be47e61); /* sceNp */
EXPORT(npScoreCreateTitleCtx, 0xb9f93bbb); /* sceNp */
EXPORT(npScoreCreateTransactionCtx, 0x6f5e8143); /* sceNp */
EXPORT(npScoreDestroyTitleCtx, 0x259113b8); /* sceNp */
EXPORT(npScoreDestroyTransactionCtx, 0xc5f4cf82); /* sceNp */
EXPORT(npScoreGetBoardInfo, 0xf4e0f607); /* sceNp */
EXPORT(npScoreGetBoardInfoAsync, 0xddce7d15); /* sceNp */
EXPORT(npScoreGetClanMemberGameData, 0x741fbf24); /* sceNp */
EXPORT(npScoreGetClanMemberGameDataAsync, 0xbef887e5); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByNpId, 0xded17c26); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByNpIdAsync, 0xe8a67160); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByNpIdPcId, 0x41ffd4f2); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByNpIdPcIdAsync, 0x433fcb30); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByRange, 0x6d4adc3b); /* sceNp */
EXPORT(npScoreGetClansMembersRankingByRangeAsync, 0x4d5e0670); /* sceNp */
EXPORT(npScoreGetClansRankingByClanId, 0x2a76895a); /* sceNp */
EXPORT(npScoreGetClansRankingByClanIdAsync, 0x227f8763); /* sceNp */
EXPORT(npScoreGetClansRankingByRange, 0xb082003b); /* sceNp */
EXPORT(npScoreGetClansRankingByRangeAsync, 0x7b7e9137); /* sceNp */
EXPORT(npScoreGetGameData, 0x3b02418d); /* sceNp */
EXPORT(npScoreGetGameDataAsync, 0xdb2e4dc2); /* sceNp */
EXPORT(npScoreGetRankingByNpId, 0x05d65dff); /* sceNp */
EXPORT(npScoreGetRankingByNpIdAsync, 0x3db7914d); /* sceNp */
EXPORT(npScoreGetRankingByNpIdPcId, 0xc3a991ee); /* sceNp */
EXPORT(npScoreGetRankingByNpIdPcIdAsync, 0xc4b6cd8f); /* sceNp */
EXPORT(npScoreGetRankingByRange, 0xfbc82301); /* sceNp */
EXPORT(npScoreGetRankingByRangeAsync, 0x21206642); /* sceNp */
EXPORT(npScoreInit, 0x32cf311f); /* sceNp */
EXPORT(npScorePollAsync, 0xa7a090e5); /* sceNp */
EXPORT(npScoreRecordGameData, 0x04ca5e6a); /* sceNp */
EXPORT(npScoreRecordGameDataAsync, 0xf76847c2); /* sceNp */
EXPORT(npScoreRecordScore, 0x1672170e); /* sceNp */
EXPORT(npScoreRecordScoreAsync, 0xf0b1e399); /* sceNp */
EXPORT(npScoreSanitizeComment, 0xf1b77918); /* sceNp */
EXPORT(npScoreSanitizeCommentAsync, 0x2cd2a1af); /* sceNp */
EXPORT(npScoreSetPlayerCharacterId, 0x2706eaa1); /* sceNp */
EXPORT(npScoreSetTimeout, 0x29dd45dc); /* sceNp */
EXPORT(npScoreTerm, 0x9851f805); /* sceNp */
EXPORT(npScoreWaitAsync, 0x1a2704f7); /* sceNp */
EXPORT(npSignalingActivateConnection, 0x60897c38); /* sceNp */
EXPORT(npSignalingAddExtendedHandler, 0x50b86d94); /* sceNp */
EXPORT(npSignalingCancelPeerNetInfo, 0x64dbb89d); /* sceNp */
EXPORT(npSignalingCreateCtx, 0x6356082e); /* sceNp */
EXPORT(npSignalingDeactivateConnection, 0xfd0eb5ae); /* sceNp */
EXPORT(npSignalingDestroyCtx, 0xa8cf8451); /* sceNp */
EXPORT(npSignalingGetConnectionFromNpId, 0xe853d388); /* sceNp */
EXPORT(npSignalingGetConnectionFromPeerAddress, 0x34ce82a0); /* sceNp */
EXPORT(npSignalingGetConnectionInfo, 0x155de760); /* sceNp */
EXPORT(npSignalingGetConnectionStatus, 0xca0a2d04); /* sceNp */
EXPORT(npSignalingGetCtxOpt, 0x2687a127); /* sceNp */
EXPORT(npSignalingGetLocalNetInfo, 0x9ad7fbd1); /* sceNp */
EXPORT(npSignalingGetPeerNetInfo, 0x75eb50cb); /* sceNp */
EXPORT(npSignalingGetPeerNetInfoResult, 0xd0958814); /* sceNp */
EXPORT(npSignalingSetCtxOpt, 0x276c72b2); /* sceNp */
EXPORT(npSignalingTerminateConnection, 0x95c7bba3); /* sceNp */
EXPORT(_sceNpSysutilClientFree, 0x816c6a5f); /* sceNp */
EXPORT(_sceNpSysutilClientMalloc, 0xee0cc40c); /* sceNp */
EXPORT(npTerm, 0x4885aa18); /* sceNp */
EXPORT(npUtilCmpNpId, 0xd208f91d); /* sceNp */
EXPORT(npUtilCmpNpIdInOrder, 0xf5ff5f31); /* sceNp */

EXPORT(_Z27_sce_np_sysutil_recv_packetiRN4cxml8DocumentERNS_7ElementE, 0x48b3774f); /* sceNp */
EXPORT(_Z27_sce_np_sysutil_send_packetiRN4cxml8DocumentE, 0x25b8bd56); /* sceNp */
EXPORT(_Z29_sce_np_sysutil_cxml_set_npidRN4cxml8DocumentERNS_7ElementEPKcPK7SceNpId, 0x9ba3e97f); /* sceNp */
EXPORT(_Z31_sce_np_sysutil_send_packet_subiRN4cxml8DocumentE, 0xad12e5c9); /* sceNp */
EXPORT(_Z32_sce_np_sysutil_cxml_prepare_docPN16sysutil_cxmlutil11FixedMemoryERN4cxml8DocumentEPKcRNS2_7ElementES6_i, 0xfd61dff5); /* sceNp */
EXPORT(_Z33_sce_np_sysutil_send_empty_packetiPN16sysutil_cxmlutil11FixedMemoryEPKcS3_, 0x1fa740db); /* sceNp */
EXPORT(_Z36_sce_np_sysutil_recv_packet_fixedmemiPN16sysutil_cxmlutil11FixedMemoryERN4cxml8DocumentERNS2_7ElementE, 0x2c5ad7b4); /* sceNp */
EXPORT(_Z37sce_np_matching_set_matching2_runningb, 0xadcc5ada); /* sceNp */
EXPORT(_Z40_sce_np_sysutil_recv_packet_fixedmem_subiPN16sysutil_cxmlutil11FixedMemoryERN4cxml8DocumentERNS2_7ElementE, 0x4299a92c); /* sceNp */


#endif
