#ifndef __EXPORTS_H__
#define __EXPORTS_H__


EXPORT(sailAuReceiverFinalize, 0xed58e3ec); /* cellSail */
EXPORT(sailAuReceiverGet, 0x3a1132ed); /* cellSail */
EXPORT(sailAuReceiverInitialize, 0x3dd9639a); /* cellSail */
EXPORT(sailAviMovieGetHeader, 0x10298371); /* cellSail */
EXPORT(sailAviMovieGetMovieInfo, 0x6e83f5c0); /* cellSail */
EXPORT(sailAviMovieGetStreamByIndex, 0x3e908c56); /* cellSail */
EXPORT(sailAviMovieGetStreamByTypeAndIndex, 0xddebd2a5); /* cellSail */
EXPORT(sailAviStreamGetHeader, 0xcc3cca60); /* cellSail */
EXPORT(sailAviStreamGetMediaType, 0xc09e2f23); /* cellSail */
EXPORT(sailDescriptorClearEs, 0xdf5553ef); /* cellSail */
EXPORT(sailDescriptorClose, 0x15fd6a2a); /* cellSail */
EXPORT(sailDescriptorCreateDatabase, 0x0abb318b); /* cellSail */
EXPORT(sailDescriptorDestroyDatabase, 0x28336e89); /* cellSail */
EXPORT(sailDescriptorGetCapabilities, 0xac9c3b1f); /* cellSail */
EXPORT(sailDescriptorGetMediaInfo, 0xbd1635f4); /* cellSail */
EXPORT(sailDescriptorGetStreamType, 0xd5f9a15b); /* cellSail */
EXPORT(sailDescriptorGetUri, 0x4c191088); /* cellSail */
EXPORT(sailDescriptorInquireCapability, 0x92590d52); /* cellSail */
EXPORT(sailDescriptorIsAutoSelection, 0x277adf21); /* cellSail */
EXPORT(sailDescriptorOpen, 0xc044fab1); /* cellSail */
EXPORT(sailDescriptorSetAutoSelection, 0x76b1a425); /* cellSail */
EXPORT(sailDescriptorSetEs, 0x0d0c2f0c); /* cellSail */
EXPORT(sailDescriptorSetParameter, 0xee94b99b); /* cellSail */
EXPORT(sailFutureFinalize, 0x9553af65); /* cellSail */
EXPORT(sailFutureGet, 0x3a2d806c); /* cellSail */
EXPORT(sailFutureInitialize, 0x4cc54f8e); /* cellSail */
EXPORT(sailFutureIsDone, 0x51ecf361); /* cellSail */
EXPORT(sailFutureReset, 0x0c4cb439); /* cellSail */
EXPORT(sailFutureSet, 0xa37fed15); /* cellSail */
EXPORT(sailGraphicsAdapterFinalize, 0x76488bb1); /* cellSail */
EXPORT(sailGraphicsAdapterGetFormat, 0xffd58aa4); /* cellSail */
EXPORT(sailGraphicsAdapterGetFrame, 0x0247c69e); /* cellSail */
EXPORT(sailGraphicsAdapterGetFrame2, 0x018281a8); /* cellSail */
EXPORT(sailGraphicsAdapterInitialize, 0x1c983864); /* cellSail */
EXPORT(sailGraphicsAdapterPtsToTimePosition, 0x1872331b); /* cellSail */
EXPORT(sailGraphicsAdapterSetPreferredFormat, 0x2e3ccb5e); /* cellSail */
EXPORT(sailGraphicsAdapterUpdateAvSync, 0x44a20e79); /* cellSail */
EXPORT(sailMemAllocatorInitialize, 0x346ebba3); /* cellSail */
EXPORT(sailMp4MovieGetBrand, 0xb980b76e); /* cellSail */
EXPORT(sailMp4MovieGetMovieInfo, 0x5783a454); /* cellSail */
EXPORT(sailMp4MovieGetTrackById, 0x85b07126); /* cellSail */
EXPORT(sailMp4MovieGetTrackByIndex, 0x5faf802b); /* cellSail */
EXPORT(sailMp4MovieGetTrackByTypeAndIndex, 0xc2d90ec9); /* cellSail */
EXPORT(sailMp4MovieIsCompatibleBrand, 0xd4049de0); /* cellSail */
EXPORT(sailMp4TrackGetTrackInfo, 0xa48be428); /* cellSail */
EXPORT(sailMp4TrackGetTrackReference, 0x5f44f64f); /* cellSail */
EXPORT(sailMp4TrackGetTrackReferenceCount, 0x72236ec1); /* cellSail */
EXPORT(sailPlayerAddDescriptor, 0x7c8dff3b); /* cellSail */
EXPORT(sailPlayerBoot, 0xbdf21b0f); /* cellSail */
EXPORT(sailPlayerCancel, 0x950d53c1); /* cellSail */
EXPORT(sailPlayerCloseEsAudio, 0xbf9b8d72); /* cellSail */
EXPORT(sailPlayerCloseEsUser, 0xaed9d6cd); /* cellSail */
EXPORT(sailPlayerCloseEsVideo, 0x07924359); /* cellSail */
EXPORT(sailPlayerCloseStream, 0x85beffcc); /* cellSail */
EXPORT(sailPlayerCreateDescriptor, 0xd7938b8d); /* cellSail */
EXPORT(sailPlayerDestroyDescriptor, 0xfc839bd4); /* cellSail */
EXPORT(sailPlayerDumpImage, 0xcc987ba6); /* cellSail */
EXPORT(sailPlayerFinalize, 0x18b4629d); /* cellSail */
EXPORT(sailPlayerGetCurrentDescriptor, 0x75fca288); /* cellSail */
EXPORT(sailPlayerGetDescriptorCount, 0x752f8585); /* cellSail */
EXPORT(sailPlayerGetParameter, 0x952269c9); /* cellSail */
EXPORT(sailPlayerGetRegisteredProtocols, 0x186b98d3); /* cellSail */
EXPORT(sailPlayerGetRepeatMode, 0x38144ecf); /* cellSail */
EXPORT(sailPlayerInitialize, 0x17932b26); /* cellSail */
EXPORT(sailPlayerInitialize2, 0x23654375); /* cellSail */
EXPORT(sailPlayerIsEsAudioMuted, 0x09de25fd); /* cellSail */
EXPORT(sailPlayerIsEsVideoMuted, 0xdbe32ed4); /* cellSail */
EXPORT(sailPlayerIsPaused, 0xaafa17b8); /* cellSail */
EXPORT(sailPlayerNext, 0x26563ddc); /* cellSail */
EXPORT(sailPlayerOpenEsAudio, 0x145f9b11); /* cellSail */
EXPORT(sailPlayerOpenEsUser, 0xa849d0a7); /* cellSail */
EXPORT(sailPlayerOpenEsVideo, 0x477501f6); /* cellSail */
EXPORT(sailPlayerOpenStream, 0x34ecc1b9); /* cellSail */
EXPORT(sailPlayerRegisterSource, 0xbedccc74); /* cellSail */
EXPORT(sailPlayerRemoveDescriptor, 0x9897fbd1); /* cellSail */
EXPORT(sailPlayerReopenEsAudio, 0x4fa5ad09); /* cellSail */
EXPORT(sailPlayerReopenEsUser, 0x7b6fa92e); /* cellSail */
EXPORT(sailPlayerReopenEsVideo, 0xf60a8a69); /* cellSail */
EXPORT(sailPlayerReplaceEventHandler, 0x47632810); /* cellSail */
EXPORT(sailPlayerSetAuReceiver, 0xf5747e1f); /* cellSail */
EXPORT(sailPlayerSetEsAudioMuted, 0x91d287f6); /* cellSail */
EXPORT(sailPlayerSetEsVideoMuted, 0xf1446a40); /* cellSail */
EXPORT(sailPlayerSetGraphicsAdapter, 0x18bcd21b); /* cellSail */
EXPORT(sailPlayerSetParameter, 0x5f7c7a6f); /* cellSail */
EXPORT(sailPlayerSetPaused, 0xd1d55a90); /* cellSail */
EXPORT(sailPlayerSetRendererAudio, 0x92eaf6ca); /* cellSail */
EXPORT(sailPlayerSetRendererVideo, 0xecf56150); /* cellSail */
EXPORT(sailPlayerSetRepeatMode, 0xfc5baf8a); /* cellSail */
EXPORT(sailPlayerSetSoundAdapter, 0x1139a206); /* cellSail */
EXPORT(sailPlayerStart, 0xe535b0d3); /* cellSail */
EXPORT(sailPlayerStop, 0xeba8d4ec); /* cellSail */
EXPORT(sailPlayerSubscribeEvent, 0x6f0b1002); /* cellSail */
EXPORT(sailPlayerUnregisterSource, 0x025b4974); /* cellSail */
EXPORT(sailPlayerUnsubscribeEvent, 0x69793952); /* cellSail */
EXPORT(sailRendererAudioFinalize, 0x06dd4174); /* cellSail */
EXPORT(sailRendererAudioInitialize, 0x67b4d01f); /* cellSail */
EXPORT(sailRendererAudioNotifyCallCompleted, 0xb7b4ecee); /* cellSail */
EXPORT(sailRendererAudioNotifyFrameDone, 0xf841a537); /* cellSail */
EXPORT(sailRendererAudioNotifyOutputEos, 0x325039b9); /* cellSail */
EXPORT(sailRendererVideoFinalize, 0x47055fea); /* cellSail */
EXPORT(sailRendererVideoInitialize, 0x8d1ff475); /* cellSail */
EXPORT(sailRendererVideoNotifyCallCompleted, 0x954f48f8); /* cellSail */
EXPORT(sailRendererVideoNotifyFrameDone, 0x5f77e8df); /* cellSail */
EXPORT(sailRendererVideoNotifyOutputEos, 0xdff1cda2); /* cellSail */
EXPORT(sailSoundAdapterFinalize, 0xd1462438); /* cellSail */
EXPORT(sailSoundAdapterGetFormat, 0xf25f197d); /* cellSail */
EXPORT(sailSoundAdapterGetFrame, 0x7eb8d6b5); /* cellSail */
EXPORT(sailSoundAdapterInitialize, 0x3d0d3b72); /* cellSail */
EXPORT(sailSoundAdapterPtsToTimePosition, 0x4ae979df); /* cellSail */
EXPORT(sailSoundAdapterSetPreferredFormat, 0x1c9d5e5a); /* cellSail */
EXPORT(sailSoundAdapterUpdateAvSync, 0xeec22809); /* cellSail */
EXPORT(sailSourceFinalize, 0xee724c99); /* cellSail */
EXPORT(sailSourceInitialize, 0x9d30bdce); /* cellSail */
EXPORT(sailSourceNotifyCallCompleted, 0x764ec2d2); /* cellSail */
EXPORT(sailSourceNotifyInputEos, 0x54c53688); /* cellSail */
EXPORT(sailSourceNotifyMediaStateChanged, 0xf4009a94); /* cellSail */
EXPORT(sailSourceNotifySessionError, 0xf289f0cd); /* cellSail */
EXPORT(sailSourceNotifyStreamOut, 0x95ee1695); /* cellSail */
EXPORT(sailSourceSetDiagHandler, 0xbdb2251a); /* cellSail */


#endif
